site_name: VMSLAB HOMELAB NOTES
site_url: https://docs.vmslab.com
copyright: Copyright &copy; 2024 - 2025 Vidjinnangni Grégory Thoto
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vidjinnangni/vmslab-homelab
    - icon: fontawesome/solid/paper-plane
      link: mailto:<gregory.thoto@gmail.com>


repo_url: https://github.com/vidjinnangni/vmslab-homelab

theme:
  favicon: ../Images/vmslab-homelab.png
  logo: ../Images/vmslab-homelab-white.png
  homepage: https://docs.vmslab.com
  name: material
  palette:
    primary: deep purple
    accent: deep purple
  font:
    text: 'Nunito'
    code: 'Nunito'
  features:
    - navigation.top
    - navigation.footer


markdown_extensions:
  - pymdownx.snippets: